### PR TITLE
Fix candidate request after matchmaker won

### PR DESCRIPTION
**Pull request by Kevin-Jin**
Fix the order of statements so that if the score is 1, it is sent to the matchmaker but the matchmaker does not need to respond with a new candidate.

### CODE REVIEW

**Comment by vighneshbirodkar** [comment]
Thanks for working on this. If the score is 1 the architect will exit and both players processes will be killed anyways. Therefore I don't think this is necessary.

**Comment by Kevin-Jin** [comment]
The problem I have with this is that I close the connection once I receive a score of 1 and that causes me to lose because the architect expects me to send another guess rather than closing the  @connection. My fix is to send the same candidate after the server tells me that my score is 1. Sure it's an easy fix on my end, but it's a bit of a kludge and others might also get confused.

More specifically, this isn't a problem if the matchmaker's first guess gives a score of 1 but if his second or later guess does.

The log looks like this:
[92mMathmacker got score 1.000000[0m
[94mReading weights from M[0m
[94mWeights recieved are: ''[0m
[91mWeights sent by M not truncated by '\n'[0m
[91mM looses due to their mistake[0m

**Comment by Kevin-Jin** [comment]
I also have a similar problem with the "person" end that only occurs when the first guess is the correct guess. Closing the connection before repeating a response causes the architect to crash.

**Comment by Kevin-Jin** [comment]
Also, should the person receive the first guess twice? I noticed that

```
person.send_guess_and_get_update(matchmaker.weight_guess)
```

Is called twice on the same weight_guess, before the matchmaker has a chance to change it.

**Comment by vighneshbirodkar** [comment]
Thanks @Kevin-Jin Merged your changes

**Pull request merged**
